version: "3.8"

services:
  authdb:
    image: postgres:16-alpine
    container_name: authdb
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
    volumes:
      - authdb_data:/var/lib/postgresql/data
    networks:
      - auth_net

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - authdb
    ports:
      - "10001:10001"
    networks:
      - auth_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: nardowilli@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwerty123
    ports:
      - "5050:80"
    depends_on:
      - authdb
    networks:
      - auth_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  authdb_data:
  pgadmin_data:

networks:
  auth_net:
